[tool.poetry]
name = "proyecto2"
version = "0.1.0"
description = "Mi segundo proyecto de ciencia de datos"
authors = ["dfbat <dfbatrol@hotmail.come.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
